import { create } from 'zustand'

export type PaymentType = 'cash' | 'card' | 'payme' | 'click' | 'bank_transfer' | 'terminal' | 'discount' | 'coupon'
export type PaymentStatus = 'paid' | 'refunded' | 'pending'

export interface PaymentRecord {
  id: string
  studentId: string
  studentName: string
  course: string
  paymentType: PaymentType
  amount: number
  date: string
  operator: string
  status: PaymentStatus
  receipt?: string
  notes?: string
}

interface PaymentsStore {
  open: boolean
  payments: PaymentRecord[]
  data: PaymentRecord | null
  onOpen: (data?: PaymentRecord | null) => void
  onClose: () => void
  addPayment: (payment: Omit<PaymentRecord, 'id'>) => void
  updatePayment: (payment: PaymentRecord) => void
  deletePayment: (id: string) => void
}

export const PAYMENT_TYPE_LABELS_UZ: Record<PaymentType, string> = {
  cash: 'Naqd',
  card: 'Karta',
  payme: 'Payme',
  click: 'Click',
  bank_transfer: 'Bank o\'tkazmasi',
  terminal: 'Terminal',
  discount: 'Chegirma',
  coupon: 'Kupon',
}

export const PAYMENT_STATUS_LABELS_UZ: Record<PaymentStatus, string> = {
  paid: 'To\'langan',
  refunded: 'Qaytarilgan',
  pending: 'Kutilmoqda',
}

export const usePaymentsStore = create<PaymentsStore>((set, get) => ({
  open: false,
  payments: [
    {
      id: '1',
      studentId: '1',
      studentName: 'Ali Ahmadov',
      course: 'Ona tili - Boshlang\'ich',
      paymentType: 'cash',
      amount: 350000,
      date: '2024-01-15',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-001',
      notes: 'Yanvar oyi uchun to\'liq to\'lov',
    },
    {
      id: '2',
      studentId: '2',
      studentName: 'Gulnoza Karimova',
      course: 'English - Beginner',
      paymentType: 'payme',
      amount: 450000,
      date: '2024-01-20',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-002',
      notes: 'Yanvar oyi uchun to\'lov',
    },
    {
      id: '3',
      studentId: '3',
      studentName: 'Sardor Valiyev',
      course: 'English - Intermediate',
      paymentType: 'card',
      amount: 500000,
      date: '2024-01-18',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-003',
      notes: 'Yanvar oyi uchun to\'lov',
    },
    {
      id: '4',
      studentId: '4',
      studentName: 'Dilshod Toshmatov',
      course: 'English - Advanced',
      paymentType: 'click',
      amount: 550000,
      date: '2024-01-22',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-004',
      notes: 'Yanvar oyi uchun to\'lov',
    },
    {
      id: '5',
      studentId: '5',
      studentName: 'Malika Yusupova',
      course: 'IELTS tayyorlov',
      paymentType: 'payme',
      amount: 650000,
      date: '2024-01-25',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-005',
      notes: 'Yanvar oyi uchun to\'lov',
    },
    {
      id: '6',
      studentId: '6',
      studentName: 'Feruza Alimova',
      course: 'Ona tili - O\'rta',
      paymentType: 'cash',
      amount: 400000,
      date: '2024-01-16',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-006',
      notes: 'Yanvar oyi uchun to\'lov',
    },
    {
      id: '7',
      studentId: '7',
      studentName: 'Bobur Ismoilov',
      course: 'Ona tili - Yuqori',
      paymentType: 'card',
      amount: 450000,
      date: '2024-01-19',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-007',
      notes: 'Yanvar oyi uchun to\'lov',
    },
    {
      id: '8',
      studentId: '8',
      studentName: 'Nigora Xasanova',
      course: 'Rus tili - Boshlang\'ich',
      paymentType: 'payme',
      amount: 400000,
      date: '2024-01-21',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-008',
      notes: 'Yanvar oyi uchun to\'lov',
    },
    {
      id: '9',
      studentId: '9',
      studentName: 'Azizbek Usmonov',
      course: 'Rus tili - O\'rta',
      paymentType: 'cash',
      amount: 450000,
      date: '2024-01-23',
      operator: 'Admin',
      status: 'pending',
      receipt: 'REC-009',
      notes: 'Kutilmoqda - qisman to\'lov',
    },
    {
      id: '10',
      studentId: '10',
      studentName: 'Javohir Karimov',
      course: 'Matematika - 5-9 sinf',
      paymentType: 'click',
      amount: 400000,
      date: '2024-01-17',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-010',
      notes: 'Yanvar oyi uchun to\'lov',
    },
    {
      id: '11',
      studentId: '11',
      studentName: 'Kamola Rahimova',
      course: 'Matematika - 10-11 sinf',
      paymentType: 'card',
      amount: 500000,
      date: '2024-01-24',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-011',
      notes: 'Yanvar oyi uchun to\'lov',
    },
    {
      id: '12',
      studentId: '12',
      studentName: 'Shohruh Mirzayev',
      course: 'Fizika - O\'rta maktab',
      paymentType: 'payme',
      amount: 450000,
      date: '2024-01-26',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-012',
      notes: 'Yanvar oyi uchun to\'lov',
    },
    {
      id: '13',
      studentId: '13',
      studentName: 'Dilshoda Toshmatova',
      course: 'Kimyo - O\'rta maktab',
      paymentType: 'cash',
      amount: 450000,
      date: '2024-01-27',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-013',
      notes: 'Yanvar oyi uchun to\'lov',
    },
    {
      id: '14',
      studentId: '14',
      studentName: 'Madina Sobirova',
      course: 'Biologiya - O\'rta maktab',
      paymentType: 'click',
      amount: 400000,
      date: '2024-01-28',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-014',
      notes: 'Yanvar oyi uchun to\'lov',
    },
    {
      id: '15',
      studentId: '15',
      studentName: 'Rustam Abdurahmonov',
      course: 'Tarix - O\'zbekiston tarixi',
      paymentType: 'card',
      amount: 350000,
      date: '2024-01-29',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-015',
      notes: 'Yanvar oyi uchun to\'lov',
    },
    {
      id: '16',
      studentId: '16',
      studentName: 'Zarina Qodirova',
      course: 'English - Kids (5-8 yosh)',
      paymentType: 'payme',
      amount: 400000,
      date: '2024-01-30',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-016',
      notes: 'Yanvar oyi uchun to\'lov',
    },
    {
      id: '17',
      studentId: '17',
      studentName: 'Farhod Jalilov',
      course: 'English - Teens (13-17 yosh)',
      paymentType: 'cash',
      amount: 480000,
      date: '2024-02-01',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-017',
      notes: 'Fevral oyi uchun to\'lov',
    },
    {
      id: '18',
      studentId: '18',
      studentName: 'Yulduz Toshmatova',
      course: 'Ona tili - Imtihon tayyorlov',
      paymentType: 'card',
      amount: 500000,
      date: '2024-02-02',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-018',
      notes: 'Fevral oyi uchun to\'lov',
    },
    {
      id: '19',
      studentId: '19',
      studentName: 'Nodira Xamidova',
      course: 'English Conversation',
      paymentType: 'click',
      amount: 450000,
      date: '2024-02-03',
      operator: 'Admin',
      status: 'pending',
      receipt: 'REC-019',
      notes: 'Kutilmoqda - to\'lov jarayonda',
    },
    {
      id: '20',
      studentId: '20',
      studentName: 'Sanjar Rahimov',
      course: 'Rus tili - Imtihon tayyorlov',
      paymentType: 'payme',
      amount: 500000,
      date: '2024-02-04',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-020',
      notes: 'Fevral oyi uchun to\'lov',
    },
    {
      id: '21',
      studentId: '1',
      studentName: 'Ali Ahmadov',
      course: 'Ona tili - Boshlang\'ich',
      paymentType: 'cash',
      amount: 350000,
      date: '2024-02-15',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-021',
      notes: 'Fevral oyi uchun to\'lov',
    },
    {
      id: '22',
      studentId: '3',
      studentName: 'Sardor Valiyev',
      course: 'English - Intermediate',
      paymentType: 'card',
      amount: 500000,
      date: '2024-02-18',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-022',
      notes: 'Fevral oyi uchun to\'lov',
    },
    {
      id: '23',
      studentId: '5',
      studentName: 'Malika Yusupova',
      course: 'IELTS tayyorlov',
      paymentType: 'payme',
      amount: 650000,
      date: '2024-02-25',
      operator: 'Admin',
      status: 'refunded',
      receipt: 'REC-023',
      notes: 'Qaytarilgan - talaba kursni tark etdi',
    },
    {
      id: '24',
      studentId: '8',
      studentName: 'Nigora Xasanova',
      course: 'Rus tili - Boshlang\'ich',
      paymentType: 'cash',
      amount: 400000,
      date: '2024-02-21',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-024',
      notes: 'Fevral oyi uchun to\'lov',
    },
    {
      id: '25',
      studentId: '11',
      studentName: 'Kamola Rahimova',
      course: 'Matematika - 10-11 sinf',
      paymentType: 'terminal',
      amount: 500000,
      date: '2024-02-24',
      operator: 'Admin',
      status: 'paid',
      receipt: 'REC-025',
      notes: 'Fevral oyi uchun to\'lov - terminal orqali',
    },
  ],
  data: null,
  onOpen: (data?: PaymentRecord | null) => set({ open: true, data: data || null }),
  onClose: () => set({ open: false, data: null }),
  addPayment: (payment) => {
    const newPayment: PaymentRecord = {
      id: Date.now().toString(),
      ...payment,
    }
    set({ payments: [...get().payments, newPayment], open: false, data: null })
  },
  updatePayment: (payment) => {
    set({
      payments: get().payments.map((p) => (p.id === payment.id ? payment : p)),
      open: false,
      data: null,
    })
  },
  deletePayment: (id) => {
    set({ payments: get().payments.filter((p) => p.id !== id) })
  },
}))